# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blocks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blocks.proto',
  package='blocks',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x62locks.proto\x12\x06\x62locks\"o\n\x06module\x12\x1d\n\x03\x66uc\x18\x01 \x03(\x0b\x32\x10.blocks.Function\x12\x15\n\ntext_start\x18\x02 \x01(\x04:\x01\x30\x12\x13\n\x08text_end\x18\x03 \x01(\x04:\x01\x30\x12\x1a\n\x0bsplit_block\x18\x04 \x01(\x08:\x05\x66\x61lse\"w\n\x08\x46unction\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x1e\n\x02\x62\x62\x18\x02 \x03(\x0b\x32\x12.blocks.BasicBlock\x12.\n\x0e\x63\x61lledFunction\x18\x03 \x03(\x0b\x32\x16.blocks.CalledFunction\x12\x0f\n\x04type\x18\x04 \x01(\r:\x01\x30\"\x1c\n\x0e\x43\x61lledFunction\x12\n\n\x02va\x18\x01 \x02(\x04\"\x13\n\x05\x43hild\x12\n\n\x02va\x18\x01 \x02(\x04\"*\n\x0bInstruction\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x0f\n\x04size\x18\x02 \x01(\r:\x01\x30\"\xa7\x01\n\nBasicBlock\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x0e\n\x06parent\x18\x02 \x02(\x04\x12\x1c\n\x05\x63hild\x18\x03 \x03(\x0b\x32\r.blocks.Child\x12)\n\x0cinstructions\x18\x04 \x03(\x0b\x32\x13.blocks.Instruction\x12\x0f\n\x04size\x18\x05 \x01(\r:\x01\x30\x12\x12\n\x07padding\x18\x06 \x01(\r:\x01\x30\x12\x0f\n\x04type\x18\x07 \x01(\r:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODULE = _descriptor.Descriptor(
  name='module',
  full_name='blocks.module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fuc', full_name='blocks.module.fuc', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_start', full_name='blocks.module.text_start', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_end', full_name='blocks.module.text_end', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='split_block', full_name='blocks.module.split_block', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=135,
)


_FUNCTION = _descriptor.Descriptor(
  name='Function',
  full_name='blocks.Function',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='blocks.Function.va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bb', full_name='blocks.Function.bb', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calledFunction', full_name='blocks.Function.calledFunction', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='blocks.Function.type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=256,
)


_CALLEDFUNCTION = _descriptor.Descriptor(
  name='CalledFunction',
  full_name='blocks.CalledFunction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='blocks.CalledFunction.va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=286,
)


_CHILD = _descriptor.Descriptor(
  name='Child',
  full_name='blocks.Child',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='blocks.Child.va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=307,
)


_INSTRUCTION = _descriptor.Descriptor(
  name='Instruction',
  full_name='blocks.Instruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='blocks.Instruction.va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='blocks.Instruction.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=351,
)


_BASICBLOCK = _descriptor.Descriptor(
  name='BasicBlock',
  full_name='blocks.BasicBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='blocks.BasicBlock.va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='blocks.BasicBlock.parent', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child', full_name='blocks.BasicBlock.child', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='blocks.BasicBlock.instructions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='blocks.BasicBlock.size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding', full_name='blocks.BasicBlock.padding', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='blocks.BasicBlock.type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=521,
)

_MODULE.fields_by_name['fuc'].message_type = _FUNCTION
_FUNCTION.fields_by_name['bb'].message_type = _BASICBLOCK
_FUNCTION.fields_by_name['calledFunction'].message_type = _CALLEDFUNCTION
_BASICBLOCK.fields_by_name['child'].message_type = _CHILD
_BASICBLOCK.fields_by_name['instructions'].message_type = _INSTRUCTION
DESCRIPTOR.message_types_by_name['module'] = _MODULE
DESCRIPTOR.message_types_by_name['Function'] = _FUNCTION
DESCRIPTOR.message_types_by_name['CalledFunction'] = _CALLEDFUNCTION
DESCRIPTOR.message_types_by_name['Child'] = _CHILD
DESCRIPTOR.message_types_by_name['Instruction'] = _INSTRUCTION
DESCRIPTOR.message_types_by_name['BasicBlock'] = _BASICBLOCK

module = _reflection.GeneratedProtocolMessageType('module', (_message.Message,), dict(
  DESCRIPTOR = _MODULE,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.module)
  ))
_sym_db.RegisterMessage(module)

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTION,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Function)
  ))
_sym_db.RegisterMessage(Function)

CalledFunction = _reflection.GeneratedProtocolMessageType('CalledFunction', (_message.Message,), dict(
  DESCRIPTOR = _CALLEDFUNCTION,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.CalledFunction)
  ))
_sym_db.RegisterMessage(CalledFunction)

Child = _reflection.GeneratedProtocolMessageType('Child', (_message.Message,), dict(
  DESCRIPTOR = _CHILD,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Child)
  ))
_sym_db.RegisterMessage(Child)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUCTION,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Instruction)
  ))
_sym_db.RegisterMessage(Instruction)

BasicBlock = _reflection.GeneratedProtocolMessageType('BasicBlock', (_message.Message,), dict(
  DESCRIPTOR = _BASICBLOCK,
  __module__ = 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.BasicBlock)
  ))
_sym_db.RegisterMessage(BasicBlock)


# @@protoc_insertion_point(module_scope)
