// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: refInf.proto

#ifndef PROTOBUF_INCLUDED_refInf_2eproto
#define PROTOBUF_INCLUDED_refInf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_refInf_2eproto 

namespace protobuf_refInf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_refInf_2eproto
namespace RefInf {
class RefList;
class RefListDefaultTypeInternal;
extern RefListDefaultTypeInternal _RefList_default_instance_;
class Reference;
class ReferenceDefaultTypeInternal;
extern ReferenceDefaultTypeInternal _Reference_default_instance_;
}  // namespace RefInf
namespace google {
namespace protobuf {
template<> ::RefInf::RefList* Arena::CreateMaybeMessage<::RefInf::RefList>(Arena*);
template<> ::RefInf::Reference* Arena::CreateMaybeMessage<::RefInf::Reference>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace RefInf {

enum Reference_RefKind {
  Reference_RefKind_C2C = 0,
  Reference_RefKind_C2D = 1,
  Reference_RefKind_D2C = 2,
  Reference_RefKind_D2D = 3
};
bool Reference_RefKind_IsValid(int value);
const Reference_RefKind Reference_RefKind_RefKind_MIN = Reference_RefKind_C2C;
const Reference_RefKind Reference_RefKind_RefKind_MAX = Reference_RefKind_D2D;
const int Reference_RefKind_RefKind_ARRAYSIZE = Reference_RefKind_RefKind_MAX + 1;

const ::google::protobuf::EnumDescriptor* Reference_RefKind_descriptor();
inline const ::std::string& Reference_RefKind_Name(Reference_RefKind value) {
  return ::google::protobuf::internal::NameOfEnum(
    Reference_RefKind_descriptor(), value);
}
inline bool Reference_RefKind_Parse(
    const ::std::string& name, Reference_RefKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Reference_RefKind>(
    Reference_RefKind_descriptor(), name, value);
}
// ===================================================================

class RefList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RefInf.RefList) */ {
 public:
  RefList();
  virtual ~RefList();

  RefList(const RefList& from);

  inline RefList& operator=(const RefList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RefList(RefList&& from) noexcept
    : RefList() {
    *this = ::std::move(from);
  }

  inline RefList& operator=(RefList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RefList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RefList* internal_default_instance() {
    return reinterpret_cast<const RefList*>(
               &_RefList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RefList* other);
  friend void swap(RefList& a, RefList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RefList* New() const final {
    return CreateMaybeMessage<RefList>(NULL);
  }

  RefList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RefList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RefList& from);
  void MergeFrom(const RefList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RefList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .RefInf.Reference ref = 1;
  int ref_size() const;
  void clear_ref();
  static const int kRefFieldNumber = 1;
  ::RefInf::Reference* mutable_ref(int index);
  ::google::protobuf::RepeatedPtrField< ::RefInf::Reference >*
      mutable_ref();
  const ::RefInf::Reference& ref(int index) const;
  ::RefInf::Reference* add_ref();
  const ::google::protobuf::RepeatedPtrField< ::RefInf::Reference >&
      ref() const;

  // optional uint64 text_start = 2 [default = 0];
  bool has_text_start() const;
  void clear_text_start();
  static const int kTextStartFieldNumber = 2;
  ::google::protobuf::uint64 text_start() const;
  void set_text_start(::google::protobuf::uint64 value);

  // optional uint64 text_end = 3 [default = 0];
  bool has_text_end() const;
  void clear_text_end();
  static const int kTextEndFieldNumber = 3;
  ::google::protobuf::uint64 text_end() const;
  void set_text_end(::google::protobuf::uint64 value);

  // optional uint64 rodata_start = 4 [default = 0];
  bool has_rodata_start() const;
  void clear_rodata_start();
  static const int kRodataStartFieldNumber = 4;
  ::google::protobuf::uint64 rodata_start() const;
  void set_rodata_start(::google::protobuf::uint64 value);

  // optional uint64 rodata_end = 5 [default = 0];
  bool has_rodata_end() const;
  void clear_rodata_end();
  static const int kRodataEndFieldNumber = 5;
  ::google::protobuf::uint64 rodata_end() const;
  void set_rodata_end(::google::protobuf::uint64 value);

  // optional uint64 data_start = 6 [default = 0];
  bool has_data_start() const;
  void clear_data_start();
  static const int kDataStartFieldNumber = 6;
  ::google::protobuf::uint64 data_start() const;
  void set_data_start(::google::protobuf::uint64 value);

  // optional uint64 data_end = 7 [default = 0];
  bool has_data_end() const;
  void clear_data_end();
  static const int kDataEndFieldNumber = 7;
  ::google::protobuf::uint64 data_end() const;
  void set_data_end(::google::protobuf::uint64 value);

  // optional uint64 datarel_start = 8 [default = 0];
  bool has_datarel_start() const;
  void clear_datarel_start();
  static const int kDatarelStartFieldNumber = 8;
  ::google::protobuf::uint64 datarel_start() const;
  void set_datarel_start(::google::protobuf::uint64 value);

  // optional uint64 datarel_end = 9 [default = 0];
  bool has_datarel_end() const;
  void clear_datarel_end();
  static const int kDatarelEndFieldNumber = 9;
  ::google::protobuf::uint64 datarel_end() const;
  void set_datarel_end(::google::protobuf::uint64 value);

  // optional uint64 initarray_start = 10 [default = 0];
  bool has_initarray_start() const;
  void clear_initarray_start();
  static const int kInitarrayStartFieldNumber = 10;
  ::google::protobuf::uint64 initarray_start() const;
  void set_initarray_start(::google::protobuf::uint64 value);

  // optional uint64 initarray_end = 11 [default = 0];
  bool has_initarray_end() const;
  void clear_initarray_end();
  static const int kInitarrayEndFieldNumber = 11;
  ::google::protobuf::uint64 initarray_end() const;
  void set_initarray_end(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RefInf.RefList)
 private:
  void set_has_text_start();
  void clear_has_text_start();
  void set_has_text_end();
  void clear_has_text_end();
  void set_has_rodata_start();
  void clear_has_rodata_start();
  void set_has_rodata_end();
  void clear_has_rodata_end();
  void set_has_data_start();
  void clear_has_data_start();
  void set_has_data_end();
  void clear_has_data_end();
  void set_has_datarel_start();
  void clear_has_datarel_start();
  void set_has_datarel_end();
  void clear_has_datarel_end();
  void set_has_initarray_start();
  void clear_has_initarray_start();
  void set_has_initarray_end();
  void clear_has_initarray_end();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::RefInf::Reference > ref_;
  ::google::protobuf::uint64 text_start_;
  ::google::protobuf::uint64 text_end_;
  ::google::protobuf::uint64 rodata_start_;
  ::google::protobuf::uint64 rodata_end_;
  ::google::protobuf::uint64 data_start_;
  ::google::protobuf::uint64 data_end_;
  ::google::protobuf::uint64 datarel_start_;
  ::google::protobuf::uint64 datarel_end_;
  ::google::protobuf::uint64 initarray_start_;
  ::google::protobuf::uint64 initarray_end_;
  friend struct ::protobuf_refInf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Reference : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RefInf.Reference) */ {
 public:
  Reference();
  virtual ~Reference();

  Reference(const Reference& from);

  inline Reference& operator=(const Reference& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Reference(Reference&& from) noexcept
    : Reference() {
    *this = ::std::move(from);
  }

  inline Reference& operator=(Reference&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reference& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Reference* internal_default_instance() {
    return reinterpret_cast<const Reference*>(
               &_Reference_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Reference* other);
  friend void swap(Reference& a, Reference& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Reference* New() const final {
    return CreateMaybeMessage<Reference>(NULL);
  }

  Reference* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Reference>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Reference& from);
  void MergeFrom(const Reference& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reference* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Reference_RefKind RefKind;
  static const RefKind C2C =
    Reference_RefKind_C2C;
  static const RefKind C2D =
    Reference_RefKind_C2D;
  static const RefKind D2C =
    Reference_RefKind_D2C;
  static const RefKind D2D =
    Reference_RefKind_D2D;
  static inline bool RefKind_IsValid(int value) {
    return Reference_RefKind_IsValid(value);
  }
  static const RefKind RefKind_MIN =
    Reference_RefKind_RefKind_MIN;
  static const RefKind RefKind_MAX =
    Reference_RefKind_RefKind_MAX;
  static const int RefKind_ARRAYSIZE =
    Reference_RefKind_RefKind_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RefKind_descriptor() {
    return Reference_RefKind_descriptor();
  }
  static inline const ::std::string& RefKind_Name(RefKind value) {
    return Reference_RefKind_Name(value);
  }
  static inline bool RefKind_Parse(const ::std::string& name,
      RefKind* value) {
    return Reference_RefKind_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint64 ref_va = 1;
  bool has_ref_va() const;
  void clear_ref_va();
  static const int kRefVaFieldNumber = 1;
  ::google::protobuf::uint64 ref_va() const;
  void set_ref_va(::google::protobuf::uint64 value);

  // optional uint64 target_va = 3;
  bool has_target_va() const;
  void clear_target_va();
  static const int kTargetVaFieldNumber = 3;
  ::google::protobuf::uint64 target_va() const;
  void set_target_va(::google::protobuf::uint64 value);

  // required uint32 ref_size = 2;
  bool has_ref_size() const;
  void clear_ref_size();
  static const int kRefSizeFieldNumber = 2;
  ::google::protobuf::uint32 ref_size() const;
  void set_ref_size(::google::protobuf::uint32 value);

  // optional .RefInf.Reference.RefKind kind = 4;
  bool has_kind() const;
  void clear_kind();
  static const int kKindFieldNumber = 4;
  ::RefInf::Reference_RefKind kind() const;
  void set_kind(::RefInf::Reference_RefKind value);

  // optional bool jt_entry = 5;
  bool has_jt_entry() const;
  void clear_jt_entry();
  static const int kJtEntryFieldNumber = 5;
  bool jt_entry() const;
  void set_jt_entry(bool value);

  // optional bool is_rela = 6;
  bool has_is_rela() const;
  void clear_is_rela();
  static const int kIsRelaFieldNumber = 6;
  bool is_rela() const;
  void set_is_rela(bool value);

  // @@protoc_insertion_point(class_scope:RefInf.Reference)
 private:
  void set_has_ref_va();
  void clear_has_ref_va();
  void set_has_ref_size();
  void clear_has_ref_size();
  void set_has_target_va();
  void clear_has_target_va();
  void set_has_kind();
  void clear_has_kind();
  void set_has_jt_entry();
  void clear_has_jt_entry();
  void set_has_is_rela();
  void clear_has_is_rela();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 ref_va_;
  ::google::protobuf::uint64 target_va_;
  ::google::protobuf::uint32 ref_size_;
  int kind_;
  bool jt_entry_;
  bool is_rela_;
  friend struct ::protobuf_refInf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RefList

// repeated .RefInf.Reference ref = 1;
inline int RefList::ref_size() const {
  return ref_.size();
}
inline void RefList::clear_ref() {
  ref_.Clear();
}
inline ::RefInf::Reference* RefList::mutable_ref(int index) {
  // @@protoc_insertion_point(field_mutable:RefInf.RefList.ref)
  return ref_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::RefInf::Reference >*
RefList::mutable_ref() {
  // @@protoc_insertion_point(field_mutable_list:RefInf.RefList.ref)
  return &ref_;
}
inline const ::RefInf::Reference& RefList::ref(int index) const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.ref)
  return ref_.Get(index);
}
inline ::RefInf::Reference* RefList::add_ref() {
  // @@protoc_insertion_point(field_add:RefInf.RefList.ref)
  return ref_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RefInf::Reference >&
RefList::ref() const {
  // @@protoc_insertion_point(field_list:RefInf.RefList.ref)
  return ref_;
}

// optional uint64 text_start = 2 [default = 0];
inline bool RefList::has_text_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RefList::set_has_text_start() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RefList::clear_has_text_start() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RefList::clear_text_start() {
  text_start_ = GOOGLE_ULONGLONG(0);
  clear_has_text_start();
}
inline ::google::protobuf::uint64 RefList::text_start() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.text_start)
  return text_start_;
}
inline void RefList::set_text_start(::google::protobuf::uint64 value) {
  set_has_text_start();
  text_start_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.text_start)
}

// optional uint64 text_end = 3 [default = 0];
inline bool RefList::has_text_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RefList::set_has_text_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RefList::clear_has_text_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RefList::clear_text_end() {
  text_end_ = GOOGLE_ULONGLONG(0);
  clear_has_text_end();
}
inline ::google::protobuf::uint64 RefList::text_end() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.text_end)
  return text_end_;
}
inline void RefList::set_text_end(::google::protobuf::uint64 value) {
  set_has_text_end();
  text_end_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.text_end)
}

// optional uint64 rodata_start = 4 [default = 0];
inline bool RefList::has_rodata_start() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RefList::set_has_rodata_start() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RefList::clear_has_rodata_start() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RefList::clear_rodata_start() {
  rodata_start_ = GOOGLE_ULONGLONG(0);
  clear_has_rodata_start();
}
inline ::google::protobuf::uint64 RefList::rodata_start() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.rodata_start)
  return rodata_start_;
}
inline void RefList::set_rodata_start(::google::protobuf::uint64 value) {
  set_has_rodata_start();
  rodata_start_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.rodata_start)
}

// optional uint64 rodata_end = 5 [default = 0];
inline bool RefList::has_rodata_end() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RefList::set_has_rodata_end() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RefList::clear_has_rodata_end() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RefList::clear_rodata_end() {
  rodata_end_ = GOOGLE_ULONGLONG(0);
  clear_has_rodata_end();
}
inline ::google::protobuf::uint64 RefList::rodata_end() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.rodata_end)
  return rodata_end_;
}
inline void RefList::set_rodata_end(::google::protobuf::uint64 value) {
  set_has_rodata_end();
  rodata_end_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.rodata_end)
}

// optional uint64 data_start = 6 [default = 0];
inline bool RefList::has_data_start() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RefList::set_has_data_start() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RefList::clear_has_data_start() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RefList::clear_data_start() {
  data_start_ = GOOGLE_ULONGLONG(0);
  clear_has_data_start();
}
inline ::google::protobuf::uint64 RefList::data_start() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.data_start)
  return data_start_;
}
inline void RefList::set_data_start(::google::protobuf::uint64 value) {
  set_has_data_start();
  data_start_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.data_start)
}

// optional uint64 data_end = 7 [default = 0];
inline bool RefList::has_data_end() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RefList::set_has_data_end() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RefList::clear_has_data_end() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RefList::clear_data_end() {
  data_end_ = GOOGLE_ULONGLONG(0);
  clear_has_data_end();
}
inline ::google::protobuf::uint64 RefList::data_end() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.data_end)
  return data_end_;
}
inline void RefList::set_data_end(::google::protobuf::uint64 value) {
  set_has_data_end();
  data_end_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.data_end)
}

// optional uint64 datarel_start = 8 [default = 0];
inline bool RefList::has_datarel_start() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RefList::set_has_datarel_start() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RefList::clear_has_datarel_start() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RefList::clear_datarel_start() {
  datarel_start_ = GOOGLE_ULONGLONG(0);
  clear_has_datarel_start();
}
inline ::google::protobuf::uint64 RefList::datarel_start() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.datarel_start)
  return datarel_start_;
}
inline void RefList::set_datarel_start(::google::protobuf::uint64 value) {
  set_has_datarel_start();
  datarel_start_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.datarel_start)
}

// optional uint64 datarel_end = 9 [default = 0];
inline bool RefList::has_datarel_end() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RefList::set_has_datarel_end() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RefList::clear_has_datarel_end() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RefList::clear_datarel_end() {
  datarel_end_ = GOOGLE_ULONGLONG(0);
  clear_has_datarel_end();
}
inline ::google::protobuf::uint64 RefList::datarel_end() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.datarel_end)
  return datarel_end_;
}
inline void RefList::set_datarel_end(::google::protobuf::uint64 value) {
  set_has_datarel_end();
  datarel_end_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.datarel_end)
}

// optional uint64 initarray_start = 10 [default = 0];
inline bool RefList::has_initarray_start() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RefList::set_has_initarray_start() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RefList::clear_has_initarray_start() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RefList::clear_initarray_start() {
  initarray_start_ = GOOGLE_ULONGLONG(0);
  clear_has_initarray_start();
}
inline ::google::protobuf::uint64 RefList::initarray_start() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.initarray_start)
  return initarray_start_;
}
inline void RefList::set_initarray_start(::google::protobuf::uint64 value) {
  set_has_initarray_start();
  initarray_start_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.initarray_start)
}

// optional uint64 initarray_end = 11 [default = 0];
inline bool RefList::has_initarray_end() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RefList::set_has_initarray_end() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RefList::clear_has_initarray_end() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RefList::clear_initarray_end() {
  initarray_end_ = GOOGLE_ULONGLONG(0);
  clear_has_initarray_end();
}
inline ::google::protobuf::uint64 RefList::initarray_end() const {
  // @@protoc_insertion_point(field_get:RefInf.RefList.initarray_end)
  return initarray_end_;
}
inline void RefList::set_initarray_end(::google::protobuf::uint64 value) {
  set_has_initarray_end();
  initarray_end_ = value;
  // @@protoc_insertion_point(field_set:RefInf.RefList.initarray_end)
}

// -------------------------------------------------------------------

// Reference

// required uint64 ref_va = 1;
inline bool Reference::has_ref_va() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Reference::set_has_ref_va() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Reference::clear_has_ref_va() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Reference::clear_ref_va() {
  ref_va_ = GOOGLE_ULONGLONG(0);
  clear_has_ref_va();
}
inline ::google::protobuf::uint64 Reference::ref_va() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.ref_va)
  return ref_va_;
}
inline void Reference::set_ref_va(::google::protobuf::uint64 value) {
  set_has_ref_va();
  ref_va_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.ref_va)
}

// required uint32 ref_size = 2;
inline bool Reference::has_ref_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Reference::set_has_ref_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Reference::clear_has_ref_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Reference::clear_ref_size() {
  ref_size_ = 0u;
  clear_has_ref_size();
}
inline ::google::protobuf::uint32 Reference::ref_size() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.ref_size)
  return ref_size_;
}
inline void Reference::set_ref_size(::google::protobuf::uint32 value) {
  set_has_ref_size();
  ref_size_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.ref_size)
}

// optional uint64 target_va = 3;
inline bool Reference::has_target_va() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Reference::set_has_target_va() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Reference::clear_has_target_va() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Reference::clear_target_va() {
  target_va_ = GOOGLE_ULONGLONG(0);
  clear_has_target_va();
}
inline ::google::protobuf::uint64 Reference::target_va() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.target_va)
  return target_va_;
}
inline void Reference::set_target_va(::google::protobuf::uint64 value) {
  set_has_target_va();
  target_va_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.target_va)
}

// optional .RefInf.Reference.RefKind kind = 4;
inline bool Reference::has_kind() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Reference::set_has_kind() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Reference::clear_has_kind() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Reference::clear_kind() {
  kind_ = 0;
  clear_has_kind();
}
inline ::RefInf::Reference_RefKind Reference::kind() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.kind)
  return static_cast< ::RefInf::Reference_RefKind >(kind_);
}
inline void Reference::set_kind(::RefInf::Reference_RefKind value) {
  assert(::RefInf::Reference_RefKind_IsValid(value));
  set_has_kind();
  kind_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.kind)
}

// optional bool jt_entry = 5;
inline bool Reference::has_jt_entry() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Reference::set_has_jt_entry() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Reference::clear_has_jt_entry() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Reference::clear_jt_entry() {
  jt_entry_ = false;
  clear_has_jt_entry();
}
inline bool Reference::jt_entry() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.jt_entry)
  return jt_entry_;
}
inline void Reference::set_jt_entry(bool value) {
  set_has_jt_entry();
  jt_entry_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.jt_entry)
}

// optional bool is_rela = 6;
inline bool Reference::has_is_rela() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Reference::set_has_is_rela() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Reference::clear_has_is_rela() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Reference::clear_is_rela() {
  is_rela_ = false;
  clear_has_is_rela();
}
inline bool Reference::is_rela() const {
  // @@protoc_insertion_point(field_get:RefInf.Reference.is_rela)
  return is_rela_;
}
inline void Reference::set_is_rela(bool value) {
  set_has_is_rela();
  is_rela_ = value;
  // @@protoc_insertion_point(field_set:RefInf.Reference.is_rela)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RefInf

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::RefInf::Reference_RefKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RefInf::Reference_RefKind>() {
  return ::RefInf::Reference_RefKind_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_refInf_2eproto
