# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shuffleInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shuffleInfo.proto',
  package='ShuffleInfo',
  syntax='proto2',
  serialized_pb=_b('\n\x11shuffleInfo.proto\x12\x0bShuffleInfo\"\xeb\x07\n\x0bReorderInfo\x12\x30\n\x03\x62in\x18\x01 \x01(\x0b\x32#.ShuffleInfo.ReorderInfo.BinaryInfo\x12\x33\n\x06layout\x18\x02 \x03(\x0b\x32#.ShuffleInfo.ReorderInfo.LayoutInfo\x12\x31\n\x05\x66ixup\x18\x03 \x03(\x0b\x32\".ShuffleInfo.ReorderInfo.FixupInfo\x12\x33\n\x06source\x18\x04 \x01(\x0b\x32#.ShuffleInfo.ReorderInfo.SourceInfo\x1a\x61\n\nBinaryInfo\x12\x17\n\x0frand_obj_offset\x18\x01 \x01(\r\x12\x18\n\x10main_addr_offset\x18\x02 \x01(\r\x12\x0e\n\x06obj_sz\x18\x03 \x01(\r\x12\x10\n\x08src_type\x18\x04 \x01(\r\x1a\xad\x01\n\nLayoutInfo\x12\x0f\n\x07\x62\x62_size\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x12\n\nnum_fixups\x18\x03 \x01(\r\x12\x16\n\x0e\x62\x62_fallthrough\x18\x04 \x01(\x08\x12\x14\n\x0csection_name\x18\x05 \x01(\t\x12\x0e\n\x06offset\x18\x06 \x01(\r\x12\x14\n\x0cpadding_size\x18\x07 \x01(\r\x12\x18\n\rassemble_type\x18\x08 \x01(\r:\x01\x30\x1a\xd9\x03\n\tFixupInfo\x12;\n\x04text\x18\x01 \x03(\x0b\x32-.ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple\x12=\n\x06rodata\x18\x02 \x03(\x0b\x32-.ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple\x12;\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32-.ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple\x12>\n\x07\x64\x61tarel\x18\x04 \x03(\x0b\x32-.ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple\x12@\n\tinitarray\x18\x05 \x03(\x0b\x32-.ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple\x1a\x90\x01\n\nFixupTuple\x12\x0e\n\x06offset\x18\x01 \x02(\r\x12\x10\n\x08\x64\x65ref_sz\x18\x02 \x02(\r\x12\x0f\n\x07is_rela\x18\x03 \x02(\x08\x12\x0c\n\x04type\x18\x04 \x01(\r\x12\x14\n\x0csection_name\x18\x05 \x01(\t\x12\x16\n\x0enum_jt_entries\x18\x06 \x01(\r\x12\x13\n\x0bjt_entry_sz\x18\x07 \x01(\r\x1a\x1e\n\nSourceInfo\x12\x10\n\x08src_type\x18\x01 \x03(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REORDERINFO_BINARYINFO = _descriptor.Descriptor(
  name='BinaryInfo',
  full_name='ShuffleInfo.ReorderInfo.BinaryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rand_obj_offset', full_name='ShuffleInfo.ReorderInfo.BinaryInfo.rand_obj_offset', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_addr_offset', full_name='ShuffleInfo.ReorderInfo.BinaryInfo.main_addr_offset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obj_sz', full_name='ShuffleInfo.ReorderInfo.BinaryInfo.obj_sz', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_type', full_name='ShuffleInfo.ReorderInfo.BinaryInfo.src_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=354,
)

_REORDERINFO_LAYOUTINFO = _descriptor.Descriptor(
  name='LayoutInfo',
  full_name='ShuffleInfo.ReorderInfo.LayoutInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bb_size', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.bb_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_fixups', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.num_fixups', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bb_fallthrough', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.bb_fallthrough', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='section_name', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.section_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.offset', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding_size', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.padding_size', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assemble_type', full_name='ShuffleInfo.ReorderInfo.LayoutInfo.assemble_type', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=530,
)

_REORDERINFO_FIXUPINFO_FIXUPTUPLE = _descriptor.Descriptor(
  name='FixupTuple',
  full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.offset', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deref_sz', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.deref_sz', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_rela', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.is_rela', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='section_name', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.section_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_jt_entries', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.num_jt_entries', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jt_entry_sz', full_name='ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.jt_entry_sz', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=862,
  serialized_end=1006,
)

_REORDERINFO_FIXUPINFO = _descriptor.Descriptor(
  name='FixupInfo',
  full_name='ShuffleInfo.ReorderInfo.FixupInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ShuffleInfo.ReorderInfo.FixupInfo.text', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rodata', full_name='ShuffleInfo.ReorderInfo.FixupInfo.rodata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ShuffleInfo.ReorderInfo.FixupInfo.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datarel', full_name='ShuffleInfo.ReorderInfo.FixupInfo.datarel', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initarray', full_name='ShuffleInfo.ReorderInfo.FixupInfo.initarray', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REORDERINFO_FIXUPINFO_FIXUPTUPLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=1006,
)

_REORDERINFO_SOURCEINFO = _descriptor.Descriptor(
  name='SourceInfo',
  full_name='ShuffleInfo.ReorderInfo.SourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_type', full_name='ShuffleInfo.ReorderInfo.SourceInfo.src_type', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1008,
  serialized_end=1038,
)

_REORDERINFO = _descriptor.Descriptor(
  name='ReorderInfo',
  full_name='ShuffleInfo.ReorderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin', full_name='ShuffleInfo.ReorderInfo.bin', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layout', full_name='ShuffleInfo.ReorderInfo.layout', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixup', full_name='ShuffleInfo.ReorderInfo.fixup', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='ShuffleInfo.ReorderInfo.source', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REORDERINFO_BINARYINFO, _REORDERINFO_LAYOUTINFO, _REORDERINFO_FIXUPINFO, _REORDERINFO_SOURCEINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=1038,
)

_REORDERINFO_BINARYINFO.containing_type = _REORDERINFO
_REORDERINFO_LAYOUTINFO.containing_type = _REORDERINFO
_REORDERINFO_FIXUPINFO_FIXUPTUPLE.containing_type = _REORDERINFO_FIXUPINFO
_REORDERINFO_FIXUPINFO.fields_by_name['text'].message_type = _REORDERINFO_FIXUPINFO_FIXUPTUPLE
_REORDERINFO_FIXUPINFO.fields_by_name['rodata'].message_type = _REORDERINFO_FIXUPINFO_FIXUPTUPLE
_REORDERINFO_FIXUPINFO.fields_by_name['data'].message_type = _REORDERINFO_FIXUPINFO_FIXUPTUPLE
_REORDERINFO_FIXUPINFO.fields_by_name['datarel'].message_type = _REORDERINFO_FIXUPINFO_FIXUPTUPLE
_REORDERINFO_FIXUPINFO.fields_by_name['initarray'].message_type = _REORDERINFO_FIXUPINFO_FIXUPTUPLE
_REORDERINFO_FIXUPINFO.containing_type = _REORDERINFO
_REORDERINFO_SOURCEINFO.containing_type = _REORDERINFO
_REORDERINFO.fields_by_name['bin'].message_type = _REORDERINFO_BINARYINFO
_REORDERINFO.fields_by_name['layout'].message_type = _REORDERINFO_LAYOUTINFO
_REORDERINFO.fields_by_name['fixup'].message_type = _REORDERINFO_FIXUPINFO
_REORDERINFO.fields_by_name['source'].message_type = _REORDERINFO_SOURCEINFO
DESCRIPTOR.message_types_by_name['ReorderInfo'] = _REORDERINFO

ReorderInfo = _reflection.GeneratedProtocolMessageType('ReorderInfo', (_message.Message,), dict(

  BinaryInfo = _reflection.GeneratedProtocolMessageType('BinaryInfo', (_message.Message,), dict(
    DESCRIPTOR = _REORDERINFO_BINARYINFO,
    __module__ = 'shuffleInfo_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo.BinaryInfo)
    ))
  ,

  LayoutInfo = _reflection.GeneratedProtocolMessageType('LayoutInfo', (_message.Message,), dict(
    DESCRIPTOR = _REORDERINFO_LAYOUTINFO,
    __module__ = 'shuffleInfo_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo.LayoutInfo)
    ))
  ,

  FixupInfo = _reflection.GeneratedProtocolMessageType('FixupInfo', (_message.Message,), dict(

    FixupTuple = _reflection.GeneratedProtocolMessageType('FixupTuple', (_message.Message,), dict(
      DESCRIPTOR = _REORDERINFO_FIXUPINFO_FIXUPTUPLE,
      __module__ = 'shuffleInfo_pb2'
      # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
      ))
    ,
    DESCRIPTOR = _REORDERINFO_FIXUPINFO,
    __module__ = 'shuffleInfo_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo.FixupInfo)
    ))
  ,

  SourceInfo = _reflection.GeneratedProtocolMessageType('SourceInfo', (_message.Message,), dict(
    DESCRIPTOR = _REORDERINFO_SOURCEINFO,
    __module__ = 'shuffleInfo_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo.SourceInfo)
    ))
  ,
  DESCRIPTOR = _REORDERINFO,
  __module__ = 'shuffleInfo_pb2'
  # @@protoc_insertion_point(class_scope:ShuffleInfo.ReorderInfo)
  ))
_sym_db.RegisterMessage(ReorderInfo)
_sym_db.RegisterMessage(ReorderInfo.BinaryInfo)
_sym_db.RegisterMessage(ReorderInfo.LayoutInfo)
_sym_db.RegisterMessage(ReorderInfo.FixupInfo)
_sym_db.RegisterMessage(ReorderInfo.FixupInfo.FixupTuple)
_sym_db.RegisterMessage(ReorderInfo.SourceInfo)


# @@protoc_insertion_point(module_scope)
