# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blocks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62locks.proto\x12\x06\x62locks\"o\n\x06module\x12\x1d\n\x03\x66uc\x18\x01 \x03(\x0b\x32\x10.blocks.Function\x12\x15\n\ntext_start\x18\x02 \x01(\x04:\x01\x30\x12\x13\n\x08text_end\x18\x03 \x01(\x04:\x01\x30\x12\x1a\n\x0bsplit_block\x18\x04 \x01(\x08:\x05\x66\x61lse\"w\n\x08\x46unction\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x1e\n\x02\x62\x62\x18\x02 \x03(\x0b\x32\x12.blocks.BasicBlock\x12.\n\x0e\x63\x61lledFunction\x18\x03 \x03(\x0b\x32\x16.blocks.CalledFunction\x12\x0f\n\x04type\x18\x04 \x01(\r:\x01\x30\"\x13\n\x05\x43hild\x12\n\n\x02va\x18\x01 \x02(\x04\"j\n\x0bInstruction\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x0f\n\x04size\x18\x02 \x01(\r:\x01\x30\x12\x14\n\tcall_type\x18\x03 \x01(\r:\x01\x30\x12\x11\n\x06\x63\x61llee\x18\x04 \x01(\x04:\x01\x30\x12\x15\n\x0b\x63\x61llee_name\x18\x05 \x01(\t:\x00\"\x1c\n\x0e\x43\x61lledFunction\x12\n\n\x02va\x18\x01 \x02(\x04\"\xc1\x01\n\nBasicBlock\x12\n\n\x02va\x18\x01 \x02(\x04\x12\x0e\n\x06parent\x18\x02 \x02(\x04\x12\x1c\n\x05\x63hild\x18\x03 \x03(\x0b\x32\r.blocks.Child\x12)\n\x0cinstructions\x18\x04 \x03(\x0b\x32\x13.blocks.Instruction\x12\x0f\n\x04size\x18\x05 \x01(\r:\x01\x30\x12\x12\n\x07padding\x18\x06 \x01(\r:\x01\x30\x12\x0f\n\x04type\x18\x07 \x01(\r:\x01\x30\x12\x18\n\tterminate\x18\x08 \x01(\x08:\x05\x66\x61lse')



_MODULE = DESCRIPTOR.message_types_by_name['module']
_FUNCTION = DESCRIPTOR.message_types_by_name['Function']
_CHILD = DESCRIPTOR.message_types_by_name['Child']
_INSTRUCTION = DESCRIPTOR.message_types_by_name['Instruction']
_CALLEDFUNCTION = DESCRIPTOR.message_types_by_name['CalledFunction']
_BASICBLOCK = DESCRIPTOR.message_types_by_name['BasicBlock']
module = _reflection.GeneratedProtocolMessageType('module', (_message.Message,), {
  'DESCRIPTOR' : _MODULE,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.module)
  })
_sym_db.RegisterMessage(module)

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTION,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Function)
  })
_sym_db.RegisterMessage(Function)

Child = _reflection.GeneratedProtocolMessageType('Child', (_message.Message,), {
  'DESCRIPTOR' : _CHILD,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Child)
  })
_sym_db.RegisterMessage(Child)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTION,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.Instruction)
  })
_sym_db.RegisterMessage(Instruction)

CalledFunction = _reflection.GeneratedProtocolMessageType('CalledFunction', (_message.Message,), {
  'DESCRIPTOR' : _CALLEDFUNCTION,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.CalledFunction)
  })
_sym_db.RegisterMessage(CalledFunction)

BasicBlock = _reflection.GeneratedProtocolMessageType('BasicBlock', (_message.Message,), {
  'DESCRIPTOR' : _BASICBLOCK,
  '__module__' : 'blocks_pb2'
  # @@protoc_insertion_point(class_scope:blocks.BasicBlock)
  })
_sym_db.RegisterMessage(BasicBlock)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODULE._serialized_start=24
  _MODULE._serialized_end=135
  _FUNCTION._serialized_start=137
  _FUNCTION._serialized_end=256
  _CHILD._serialized_start=258
  _CHILD._serialized_end=277
  _INSTRUCTION._serialized_start=279
  _INSTRUCTION._serialized_end=385
  _CALLEDFUNCTION._serialized_start=387
  _CALLEDFUNCTION._serialized_end=415
  _BASICBLOCK._serialized_start=418
  _BASICBLOCK._serialized_end=611
# @@protoc_insertion_point(module_scope)
