# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: refInf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='refInf.proto',
  package='RefInf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0crefInf.proto\x12\x06RefInf\"\x99\x02\n\x07RefList\x12\x1e\n\x03ref\x18\x01 \x03(\x0b\x32\x11.RefInf.Reference\x12\x15\n\ntext_start\x18\x02 \x01(\x04:\x01\x30\x12\x13\n\x08text_end\x18\x03 \x01(\x04:\x01\x30\x12\x17\n\x0crodata_start\x18\x04 \x01(\x04:\x01\x30\x12\x15\n\nrodata_end\x18\x05 \x01(\x04:\x01\x30\x12\x15\n\ndata_start\x18\x06 \x01(\x04:\x01\x30\x12\x13\n\x08\x64\x61ta_end\x18\x07 \x01(\x04:\x01\x30\x12\x18\n\rdatarel_start\x18\x08 \x01(\x04:\x01\x30\x12\x16\n\x0b\x64\x61tarel_end\x18\t \x01(\x04:\x01\x30\x12\x1a\n\x0finitarray_start\x18\n \x01(\x04:\x01\x30\x12\x18\n\rinitarray_end\x18\x0b \x01(\x04:\x01\x30\"\xbb\x01\n\tReference\x12\x0e\n\x06ref_va\x18\x01 \x02(\x04\x12\x10\n\x08ref_size\x18\x02 \x02(\r\x12\x11\n\ttarget_va\x18\x03 \x01(\x04\x12\'\n\x04kind\x18\x04 \x01(\x0e\x32\x19.RefInf.Reference.RefKind\x12\x10\n\x08jt_entry\x18\x05 \x01(\x08\x12\x0f\n\x07is_rela\x18\x06 \x01(\x08\"-\n\x07RefKind\x12\x07\n\x03\x43\x32\x43\x10\x00\x12\x07\n\x03\x43\x32\x44\x10\x01\x12\x07\n\x03\x44\x32\x43\x10\x02\x12\x07\n\x03\x44\x32\x44\x10\x03')
)



_REFERENCE_REFKIND = _descriptor.EnumDescriptor(
  name='RefKind',
  full_name='RefInf.Reference.RefKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C2C', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2D', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D2C', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D2D', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=451,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_REFERENCE_REFKIND)


_REFLIST = _descriptor.Descriptor(
  name='RefList',
  full_name='RefInf.RefList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='RefInf.RefList.ref', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_start', full_name='RefInf.RefList.text_start', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_end', full_name='RefInf.RefList.text_end', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rodata_start', full_name='RefInf.RefList.rodata_start', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rodata_end', full_name='RefInf.RefList.rodata_end', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_start', full_name='RefInf.RefList.data_start', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_end', full_name='RefInf.RefList.data_end', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datarel_start', full_name='RefInf.RefList.datarel_start', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datarel_end', full_name='RefInf.RefList.datarel_end', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initarray_start', full_name='RefInf.RefList.initarray_start', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initarray_end', full_name='RefInf.RefList.initarray_end', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=306,
)


_REFERENCE = _descriptor.Descriptor(
  name='Reference',
  full_name='RefInf.Reference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_va', full_name='RefInf.Reference.ref_va', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref_size', full_name='RefInf.Reference.ref_size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_va', full_name='RefInf.Reference.target_va', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='RefInf.Reference.kind', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jt_entry', full_name='RefInf.Reference.jt_entry', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_rela', full_name='RefInf.Reference.is_rela', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REFERENCE_REFKIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=496,
)

_REFLIST.fields_by_name['ref'].message_type = _REFERENCE
_REFERENCE.fields_by_name['kind'].enum_type = _REFERENCE_REFKIND
_REFERENCE_REFKIND.containing_type = _REFERENCE
DESCRIPTOR.message_types_by_name['RefList'] = _REFLIST
DESCRIPTOR.message_types_by_name['Reference'] = _REFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RefList = _reflection.GeneratedProtocolMessageType('RefList', (_message.Message,), dict(
  DESCRIPTOR = _REFLIST,
  __module__ = 'refInf_pb2'
  # @@protoc_insertion_point(class_scope:RefInf.RefList)
  ))
_sym_db.RegisterMessage(RefList)

Reference = _reflection.GeneratedProtocolMessageType('Reference', (_message.Message,), dict(
  DESCRIPTOR = _REFERENCE,
  __module__ = 'refInf_pb2'
  # @@protoc_insertion_point(class_scope:RefInf.Reference)
  ))
_sym_db.RegisterMessage(Reference)


# @@protoc_insertion_point(module_scope)
